variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  DOCKER_AUTH_CONFIG: $DOCKER_CONFIG_JSON

stages:
  - build
  - deploy

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.11.0
  script:
    - kubectl create namespace $KUBECTL_NAMESPACE || true
    - kubectl config set-context --current --namespace=${KUBECTL_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - kubectl apply -f deployment.yaml
    - kubectl rollout restart deployments biovalidator
  when: manual