apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biovalidator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.ebi.ac.uk
      http:
        paths:
          - path: /biovalidator
            pathType: Prefix
            backend:
              service:
                name: biovalidator-service
                port:
                  number: 3020