apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: biovalidator
  name: biovalidator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: biovalidator
  template:
    metadata:
      labels:
        app: biovalidator
    spec:
      containers:
        - image: quay.io/ebi-ait/biovalidator:2.2.2
          imagePullPolicy: Always
          name: json-schema-validator
          ports:
            - containerPort: 3020